name: Maven Package

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn --batch-mode clean deploy -P pgpSigned sonatype -DuseSonatype=true
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPEUSER }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPEPASSWORD }}
        SIGNINGKEYID: ${{ secrets.SIGNINGKEYID }}
        SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
